# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\doron\Documents\py proprogressBarjects\Image_editor\Image plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

class Ui_plot_image(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 620)
        pixmap = QPixmap(571, 620)
        pixmap.scaled(1171, 742)
        MainWindow.setStyleSheet(f'background-image: url({pixmap.toImage()}); background-position: right; background-repeat: repeat;')
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 2, 501, 501))
        self.label.setText("")
        self.label.setObjectName("label")
        self.Button_prev = QtWidgets.QPushButton(self.centralwidget)
        self.Button_prev.setGeometry(QtCore.QRect(240, 550, 75, 23))
        self.Button_prev.setObjectName("Button_prev")
        self.Button_del = QtWidgets.QPushButton(self.centralwidget)
        self.Button_del.setGeometry(QtCore.QRect(10, 550, 75, 23))
        self.Button_del.setObjectName("Button_del")
        self.Button_next = QtWidgets.QPushButton(self.centralwidget)
        self.Button_next.setGeometry(QtCore.QRect(320, 550, 75, 23))
        self.Button_next.setObjectName("Button_next")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(6, 523, 391, 20))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_prev.setText(_translate("MainWindow", "Prev image"))
        self.Button_del.setText(_translate("MainWindow", "Delete Image"))
        self.Button_next.setText(_translate("MainWindow", "Next Image"))
        self.label_2.setText(_translate("MainWindow", "Image Path:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_plot_image()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
